name: Discord created 

on:
  push:
    branches:
      - "*"

jobs:
  send-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Discord embed
        id: create_embed
        run: |
          node_exec=$(node create-discord-embed.js)
          echo "embed=$node_exec" >> $GITHUB_ENV

      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.MY_DISCORD_WEBHOOK }}
          DISCORD_PERSONALIZED_EMBED: ${{ env.embed }}
        uses: ./

      
        
        