name: DIiscord Notification

on:
  push:
  pull_request:
  issues:



jobs:
  action:
    runs-on: ubuntu-latest
      

    steps:
      - uses: actions/checkout@v4

      - name: Create notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: ./

      - name: Get the output time
        run: echo "$debug-output"
        
