name: DIiscord Notification

on:
  push:
  pull_request:
  issues:



jobs:
  action:
    runs-on: ubuntu-latest
    
    env:
      debug-output: 
      

    steps:
      - uses: actions/checkout@v4

      - name: Create notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.MY_DISCORD_WEBHOOK }}
        uses: ./.github/actions/

      - name: Get the output time
        run: echo "$debug-output"
        
