name: DIiscord Notification

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
  issues:
  issue_comment:
  push:



jobs:
  action:
    runs-on: ubuntu-latest
      

    steps:
      - uses: actions/checkout@v4

      - name: Create notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: ./

      - name: Get the output time
        run: echo "$debug-output"
        
