name: JS Actions

on:
    push:
    pull_request:
    issues:
    issue_comment:
    pull_request_review:
    pull_request_review_comment:
    release:
    repository_dispatch:
    workflow_dispatch:

jobs:
  action:
    if: ${{ !github.event.repository.is_template }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: ha-ha
        uses: ./.github/actions/